seed: 42

models:
  separate: True
  policy:
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [512, 256, 128]
        activations: elu
    output: tanh(ACTIONS)
  target_policy:
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES
        layers: [512, 256, 128]
        activations: elu
    output: tanh(ACTIONS)
  critic:
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES_ACTIONS
        layers: [512, 256, 128]
        activations: elu
    output: ONE
  target_critic:
    class: DeterministicMixin
    clip_actions: False
    network:
      - name: net
        input: STATES_ACTIONS
        layers: [512, 256, 128]
        activations: elu
    output: ONE

memory:
  class: RandomMemory
  memory_size: 50000

agent:
  class: DDPG
  gradient_steps: 1
  batch_size: 256
  discount_factor: 0.99
  polyak: 0.005
  actor_learning_rate: 3.0e-04
  critic_learning_rate: 3.0e-04
  learning_rate_scheduler: null
  learning_rate_scheduler_kwargs: null
  state_preprocessor: RunningStandardScaler
  state_preprocessor_kwargs: null
  random_timesteps: 100
  learning_starts: 100
  grad_norm_clip: 1.0
  exploration:
    noise: OrnsteinUhlenbeckNoise
    noise_kwargs:
      theta: 0.15
      sigma: 0.20
      base_scale: 1.0
      mean: 0.0
      std: 1.0
    initial_scale: 1.0
    final_scale: 0.05
    timesteps: 20000
  rewards_shaper_scale: 0.1
  mixed_precision: False
  experiment:
    directory: "jetauto_vrrobo_manager"
    experiment_name: ""
    write_interval: auto
    checkpoint_interval: auto

trainer:
  class: SequentialTrainer
  timesteps: 40000
  environment_info: log
